- name: install nagios common
  import_tasks: install_nagios_common.yml
  tags: nagios_common

- name: install nagios core
  import_tasks: install_nagios_core.yml
  tags: nagios_core

- name: install nagios plugins
  import_tasks: install_nagios_plugins.yml
  tags: nagios_plugins

- name: update ansible defined config
  import_tasks: update_hosts.yml
  tags: nagios_update_hosts

- name: update ansible defined host specific services
  import_tasks: update_host_services.yml
  tags: nagios_update_hosts

- name: update ansible defined host_groups
  import_tasks: update_host_groups.yml
  tags: nagios_update_hosts

- name: update ansible defined contact_groups
  import_tasks: update_contact_groups.yml
  tags: nagios_update_hosts

- name: update customconfig
  import_tasks: update_custom_objects.yml
  tags: nagios_update_hosts

- name: start nagios
  systemd: name=nagios state=started
