- name: create directory for tests
  file:
    path: "{{nagios_tests_dir}}"
    state: directory
    mode: 0775
    owner: nagios
    group: nagios

- name: add contacts
  template:
    src: contacts.cfg.j2
    dest: "{{nagios_tests_dir}}/contacts.cfg"
    group: nagios
    owner: nagios
    mode: 0664
  notify: reload nagios

- name: add hosts
  template:
    src: host_services.cfg.j2
    dest: "{{nagios_tests_dir}}/host_{{ item }}.cfg"
    group: nagios
    owner: nagios
    mode: 0664
  with_items: "{{groups['all']}}"
  notify: reload nagios
